// Curated MaterialCommunityIcons names for category/subcategory icon pickers —
// brief §10 explicitly wants "no question-mark placeholder icons," so this
// constrains selection to a known-good, finance-relevant set rather than free
// text (which was the old behavior and could easily typo into a blank glyph).
const ICON_LIBRARY = [
  { name: 'food-outline', label: 'Food' },
  { name: 'silverware-fork-knife', label: 'Dining' },
  { name: 'coffee-outline', label: 'Coffee' },
  { name: 'cart-outline', label: 'Groceries' },
  { name: 'car-outline', label: 'Transport' },
  { name: 'gas-station-outline', label: 'Fuel' },
  { name: 'train-car', label: 'Commute' },
  { name: 'airplane', label: 'Travel' },
  { name: 'home-outline', label: 'Home' },
  { name: 'lightning-bolt-outline', label: 'Utilities' },
  { name: 'wifi', label: 'Internet' },
  { name: 'cellphone', label: 'Phone' },
  { name: 'shopping-outline', label: 'Shopping' },
  { name: 'tshirt-crew-outline', label: 'Clothing' },
  { name: 'movie-open-outline', label: 'Entertainment' },
  { name: 'gamepad-variant-outline', label: 'Gaming' },
  { name: 'music-note-outline', label: 'Music' },
  { name: 'book-open-variant', label: 'Education' },
  { name: 'hospital-box-outline', label: 'Health' },
  { name: 'pill', label: 'Medicine' },
  { name: 'dumbbell', label: 'Fitness' },
  { name: 'paw-outline', label: 'Pets' },
  { name: 'baby-face-outline', label: 'Kids' },
  { name: 'gift-outline', label: 'Gifts' },
  { name: 'hand-heart-outline', label: 'Charity' },
  { name: 'shield-check-outline', label: 'Insurance' },
  { name: 'file-document-outline', label: 'Taxes' },
  { name: 'bank-outline', label: 'Banking' },
  { name: 'credit-card-outline', label: 'Card' },
  { name: 'cash-multiple', label: 'Cash' },
  { name: 'briefcase-outline', label: 'Salary' },
  { name: 'laptop', label: 'Freelance' },
  { name: 'chart-line', label: 'Investment' },
  { name: 'piggy-bank-outline', label: 'Savings' },
  { name: 'hand-coin-outline', label: 'Loan' },
  { name: 'store-outline', label: 'Business' },
  { name: 'wrench-outline', label: 'Repairs' },
  { name: 'party-popper', label: 'Celebration' },
  { name: 'glass-cocktail', label: 'Drinks' },
  { name: 'dots-horizontal-circle-outline', label: 'Other' },
  { name: 'shape-outline', label: 'General' },
];

export default ICON_LIBRARY;
